language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 5.5
      env: COVERALLS=1 DEFAULT=0

    - php: 7
      env: PHPCS=1 DEFAULT=0

  allow_failures:
    - env: COVERALLS=1 DEFAULT=0

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit; fi"

  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src; fi"

  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then vendor/bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  email: false

before_deploy:
  - sh -c "curl -LSs http://box-project.github.io/box2/installer.php | php && php box.phar build"

deploy:
  provider: releases
  api_key:
    secure: qJHoOifor0HH2McbE4VJrIu/LtaG4IUyOE7mVA/4WIs6jhVEzIcLoPI39GvkfqdszUENJiCBysG/Wllo3lf0wTteclc3flt7aPpxaGt2S5L7yyYrCu3EOP6CnrUNd/2rVgRiLx8qRXXMZpRxtWTkoKBO6IxM5S8ASSzj9s2RjfM=
  file: apigen.phar
  on:
    repo: ApiGen/ApiGen
    branch: '4.1'
    tags: true

after_deploy:
  - ./update-gh-page.sh
  - ./generate-api.sh
