language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install --prefer-source

before_script:
  # php linter
  - vendor/bin/parallel-lint -e php --exclude vendor .
  # php code sniffer
  - vendor/bin/phpcs src tests --extensions=php --ignore=bootstrap --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml

script:
  - if [[ $TRAVIS_PHP_VERSION != '5.6' ]]; then vendor/bin/phpunit; fi
  # generate coverage only with latest PHP
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; fi

after_script:
  # move code coverage
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION == '5.6' ]]; php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
